# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170729_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
