# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image',
        ),
        migrations.AddField(
            model_name='page',
            name='header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
