# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
