# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 04:55
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170729_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image'),
        ),
    ]
