# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 15:28
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('pages', '0002_auto_20170829_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='custom_css',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_css', to='filer.File'),
        ),
        migrations.AddField(
            model_name='page',
            name='custom_js',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_js', to='filer.File'),
        ),
    ]
